LOAD DATA
REPLACE
INTO TABLE MY_OWNER.TABLE_PARTNER
FIELDS TERMINATED BY ','
TRAILING NULLCOLS
(
NAME_PARTNER "RTRIM (:NAME_PARTNER)",
CODE_BASE  DECIMAL EXTERNAL TERMINATED BY ',',
ID_PARTNER "RTRIM (:ID_PARTNER)",
DATE_CREATION SYSDATE 
)